services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    container_name: postgres_template_test
    ports:
      - '5432:5432'
